### ISSUE TITLE
High-level helper functions?

### ISSUE THREAD

**Issue by matthiasbeyer** [matthiasbeyer/toml-query#23]
I'm not sure whether this should be included in this crate, actually.

But I would like to add some helper functions in the spirit of:

```rust
read_str("foo.bar") -> Result<String, Error>
```

where the error indicates if the operation succeded or failed, if there was an type error or if the value is not available.

Of course, `update`, `insert`, `set` should be a thing, and this should be implemented for all supported types of `Value`.

I would make this a compiletime feature.

@TheNeikos maybe you can provide some thoughts whether this could be a nice idea?

**Comment by TheNeikos** [comment]
It does sound like something one would want to have.

What do you want to make 'compiletime' about it?

**Comment by matthiasbeyer** [comment]
I would gate it behind a feature flag...

**Comment by TheNeikos** [comment]
Ah, well why? It seems very useful.

**Comment by Michael-F-Bryan** [comment]
Would it make sense to use make `read()` and friends generic over anything which implements `serde::Deserialize`? That you can use `Value::try_from()` and `Value::try_into()` to automatically serialize/deserialize the result of a query into any serializable type.

I imagine you'd have a generic adaptor method called `insert()` which lets you insert anything which is `Serialize`, and under the hood that just calls `Value::try_into()` and immediately passes it to an `insert_value()` method (which is just the current `insert()`).

**Comment by matthiasbeyer** [comment]
@Michael-F-Bryan I have something like this in mind, though it would blow up the complexity of this crate a lot.

If you want to develop such a crate, feel free to reuse code from this code **if, and only if** the new crate is distributed under MPL2.0. :smile:
