### ISSUE TITLE
Traits should also work with Table and Array

### ISSUE THREAD

**Issue by Michael-F-Bryan** [matthiasbeyer/toml-query#34]
Would it be possible to implement the traits on a `toml` `Table`?

**Comment by matthiasbeyer** [comment]
Which traits exactly? The `TomlValueReadExt` for example?

**Comment by Michael-F-Bryan** [comment]
Yeah, I was thinking the traits for reading and inserting at the very least. 

My use case is that in `mdbook` I'm currently representing my `Config` struct as a toml file containing a bunch of pre-defined tables, plus a `rest` which contains all the other tables in the config file so arbitrary backends can hook into the config file. Instead of storing the `rest` as a `toml::Value`, I'd like to use a `Table` instead so we can statically ensure `rest` will always be a `Table` instead of checking every time it's accessed.

This is the current `Config` definition.

```rust
pub struct Config {
    /// Metadata about the book.
    pub book: BookConfig,
    pub build: BuildConfig,
    rest: Value,
}
```

**Comment by matthiasbeyer** [comment]
@Michael-F-Bryan see https://github.com/matthiasbeyer/toml-query/pull/35

**Comment by matthiasbeyer** [comment]
Closed as we develop on sourcehut now.
