### ISSUE TITLE
Make a new release of toml-query_derive

### ISSUE THREAD

**Issue by Aaron1011** [matthiasbeyer/toml-query#51]
The latest published version of `toml-query_derive` on `crates.io` depends on old versions of `syn`, `quote`, and `darling`. It would be very useful if you could make a new release of `toml-query_dervice`, since the latest `master` depends on newer (semver-incompatible) versions of these crates.

**Comment by matthiasbeyer** [comment]
I'll publish an update of the whole toml-query project until Sunday!

Feel free to ping me again if I forget this! 

Thanks for reminding me, I really value that you open these kind of issues!
